apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/composition-resource-name: eks-cluster
    crossplane.io/external-name: sample-customer
  creationTimestamp: "2023-09-30T10:20:05Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: sample-customer-jhmp4-
  generation: 2
  labels:
    app.kubernetes.io/instance: eks-import
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: sample-customer
    app.kubernetes.io/part-of: sample-customer-eks-import
    crossplane.io/claim-name: sample-customer
    crossplane.io/claim-namespace: org-sample
    crossplane.io/composite: sample-customer-jhmp4
    provider: aws
  name: sample-customer
  ownerReferences:
  - apiVersion: crossplane.giantswarm.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CompositeEksImport
    name: sample-customer-jhmp4
    uid: f3e4fa75-e761-4d54-b74e-ad18cd415761
  resourceVersion: "1754"
  uid: 3fb51335-0a91-4a57-a276-ea41219567f9
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    name: snail
  writeConnectionSecretToRef:
    name: sample-customer-eks-cluster
    namespace: org-sample
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-09-30T10:20:06Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-09-30T10:20:09Z"
    reason: Available
    status: "True"
    type: Ready
