apiVersion: crossplane.giantswarm.io/v1alpha1
kind: CompositeEksImport
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"crossplane.giantswarm.io/v1alpha1","kind":"EksImportClaim","metadata":{"annotations":{},"labels":{"owner":"honeybadger"},"name":"sample-customer","namespace":"org-sample"},"spec":{"compositionSelector":{"matchLabels":{"component":"aws-eks-importer","provider":"aws"}},"compositionUpdatePolicy":"Manual","kubernetesAdditionalLabels":{"app":"cluster-eks","app.kubernetes.io/managed-by":"crossplane","cluster-apps-operator.giantswarm.io/watching":"","cluster.x-k8s.io/watch-filter":"capi","giantswarm.io/organization":"giantswarm","giantswarm.io/service-priority":"highest"},"labels":{"app.kubernetes.io/instance":"eks-import","app.kubernetes.io/managed-by":"crossplane","provider":"aws"},"namespace":"org-sample","parameters":{"awsProviderConfigRef":"snail","clusterName":"sample-customer","kubernetesProviderConfigRef":"kubernetes-provider","nodeGroupName":"ng-1","region":"eu-central-1"}}}
  creationTimestamp: "2023-09-30T10:20:04Z"
  finalizers:
  - composite.apiextensions.crossplane.io
  generateName: sample-customer-
  generation: 4
  labels:
    crossplane.io/claim-name: sample-customer
    crossplane.io/claim-namespace: org-sample
    crossplane.io/composite: sample-customer-jhmp4
    owner: honeybadger
  name: sample-customer-jhmp4
  resourceVersion: "1718"
  uid: f3e4fa75-e761-4d54-b74e-ad18cd415761
spec:
  claimRef:
    apiVersion: crossplane.giantswarm.io/v1alpha1
    kind: EksImportClaim
    name: sample-customer
    namespace: org-sample
  compositionRef:
    name: aws-eks-import
  compositionRevisionRef:
    name: aws-eks-import-c74bb67
  compositionSelector:
    matchLabels:
      component: aws-eks-importer
      provider: aws
  compositionUpdatePolicy: Manual
  kubernetesAdditionalLabels:
    app: cluster-eks
    app.kubernetes.io/managed-by: crossplane
    cluster-apps-operator.giantswarm.io/watching: ""
    cluster.x-k8s.io/watch-filter: capi
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-priority: highest
  labels:
    app.kubernetes.io/instance: eks-import
    app.kubernetes.io/managed-by: crossplane
    provider: aws
  namespace: org-sample
  parameters:
    awsProviderConfigRef: snail
    clusterName: sample-customer
    deletionPolicy: Delete
    kubernetesProviderConfigRef: kubernetes-provider
    nodeGroupName: ng-1
    region: eu-central-1
  resourceRefs:
  - apiVersion: eks.aws.upbound.io/v1beta1
    kind: Cluster
    name: sample-customer
status:
  conditions:
  - lastTransitionTime: "2023-09-30T10:20:05Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-09-30T10:20:05Z"
    message: 'Unready resources: eks-cluster'
    reason: Creating
    status: "False"
    type: Ready
